import os  
path = r'c:\Users\Darvin7\.gemini\antigravity\playground\crm_mobile_app\lib\notifications.ts'  
with open(path, 'a', encoding='utf-8') as f:  
    f.write('\n\nexport async function scheduleInactivityReminder() {\n')  
    f.write('  try {\n')  
    f.write('    await Notifications.cancelAllScheduledNotificationsAsync();\n')  
    f.write('    const triggerInSeconds = 60;\n')  
    f.write('    await Notifications.scheduleNotificationAsync({\n')  
    f.write('      content: {\n')  
    f.write('        title: \" ­Te extra¤amos en Quantica! "??\,\n')  
    f.write('        body: \No" olvides que tienes puntos acumulados listos para canjear por "premios.\,\n')  
    f.write('        sound: true,\n')  
    f.write('      },\n')  
    f.write('      trigger: { seconds: triggerInSeconds, repeats: false },\n')  
    f.write('    });\n')  
    f.write('    console.log(\Notificacion" de inactividad programada en "\ + str(triggerInSeconds) + \" "segundos\);\n')  
    f.write('  } catch (err) {\n')  
    f.write('    console.error(\Error" programando la "notificacion:\, err);\n')  
    f.write('  }\n')  
    f.write('}\n')  
